cloud:
  aws:
    credentials:
      access-key: AKIAQLGM5YUXBRJV3PF3
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: aniruddhastorages

server:
  port: 9090